server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webvn
    username: postgres
    password: hieutm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true